### ISSUE TITLE
Sideline causing overflow

### ISSUE THREAD

**Issue by pcr910303** [emacs-lsp/lsp-ui#287] opened 2019-05-16 14:26 UTC
Sideline overflows on some situations; I'm not sure what condition causes this problem.

This file is [caldwell/build-emacs](https://github.com/caldwell/build-emacs) repo's [ensure-brew](https://github.com/caldwell/build-emacs/blob/master/ensure-brew).
<img width="1238" alt="무제" src="https://user-images.githubusercontent.com/37990858/57861572-c710ac00-7831-11e9-8939-9c4a7b86a35e.png">

**Comment by yyoncho** [comment] 2019-05-16 14:56
duplicate of https://github.com/emacs-lsp/lsp-ui/issues/285

**Closed by yyoncho** 2019-05-16 14:56 UTC
