### ISSUE TITLE
Can't resize sideline fonts

### ISSUE THREAD

**Issue by ianpan870102** [emacs-lsp/lsp-ui#580] opened 2021-03-12 06:44 UTC
I'd like the sideline fonts to be smaller. I tried almost every solution I found online, including:

```emacs-licp
(set-face-attribute 'lsp-ui-sideline-global nil :height 0.75)

; and

(custom-set-faces '(lsp-ui-sideline-global ((t (:height 0.75)))))
```

For reference, this is the font size I'd like to shrink in the screenshot below:

![image](https://user-images.githubusercontent.com/36686900/110902853-7a209280-8341-11eb-97ab-751aa71cbd13.png)

**Comment by jcs090218** [comment] 2021-03-16 04:26
By seeing the document string from variable `lsp-ui-sideline-global`,

```el
(defface lsp-ui-sideline-global
  '((t))
  "Face which apply to all overlays.
This face have a low priority over the others."
  :group 'lsp-ui-sideline)
```

Try customize variable `lsp-ui-sideline-code-action` instead.

**Comment by ianpan870102** [comment] 2021-03-17 09:20
I tried something like 
```emacs-lisp
  (custom-set-faces '(lsp-ui-sideline-code-action ((t (:height 85)))))
```
but sadly saw no effect.

**Comment by jcs090218** [comment] 2021-03-24 05:16
Duplicate of #561. See if the [comment](https://github.com/emacs-lsp/lsp-ui/issues/561#issuecomment-762746715) helps?

Close this for duplicate issue.

**Closed by jcs090218** 2021-03-24 05:16 UTC
Labels: question, ui-sideline

**Comment by ianpan870102** [comment] 2021-03-24 10:03
Unfortunately, that comment didn't help. It caused new bugs to insert text at the beginning of the buffer

**Comment by ianyepan** [comment] 2022-02-19 18:32
I tried the following snippet:

```emacs-lisp
  (set-face-attribute 'lsp-ui-sideline-global nil         :family "Segoe UI Variable Static Small" :italic t :height 0.8)
  (set-face-attribute 'lsp-ui-sideline-code-action nil    :family "Segoe UI Variable Static Small" :italic t :height 0.8)
  (set-face-attribute 'lsp-ui-sideline-symbol-info nil    :family "Segoe UI Variable Static Small" :italic t :height 0.8)
  (set-face-attribute 'lsp-ui-sideline-symbol nil         :family "Segoe UI Variable Static Small" :italic t :height 0.8)
  (set-face-attribute 'lsp-ui-sideline-current-symbol nil :family "Segoe UI Variable Static Small" :italic t :height 0.8)
```

However, only the "family" attribute is changed. I am seeing no italic or height difference. I cannot locate which face is overriding these lsp-ui faces. I even went into the lsp-ui-sideline source code to change the heights from 0.99 to 0.8 and byte compiled it, yet still no height change.

## font family changes, but no italics or height change

![image](https://user-images.githubusercontent.com/36686900/154814197-d36dcef3-3785-47af-91da-dd41c5d237d1.png)

**Comment by ianyepan** [comment] 2022-02-23 04:26
friendly ping :)
