### ISSUE TITLE
lsp-ui-doc-mode has different highlights than eldoc-mode

### ISSUE THREAD

**Issue by Yanhao** [emacs-lsp/lsp-ui#402] opened 2020-02-15 03:08 UTC
The pictures can describe this  problem very well：
the lsp-ui-doc-mode effect：
![Screen Shot 2020-02-15 at 10 59 52 AM](https://user-images.githubusercontent.com/10085564/74580860-5591a400-4fe3-11ea-8e4a-71bb19855404.png)

meantime the eldoc-mode effect
![Screen Shot 2020-02-15 at 10 59 33 AM](https://user-images.githubusercontent.com/10085564/74580869-67734700-4fe3-11ea-9b08-efd8dc392140.png)

**Comment by bryandmc** [comment] 2020-06-03 06:01
This would be a huge quality of life improvement. Some lsp modes seem to get around this, but most suffer from this issue. So it might be worth looking into how the different modes are hooking in b/c rust has colored (though not always the same as eldoc) highlighting, but python and java don't seem to have any color highlighting except maybe links.. Just wanted to contribute my findings regarding this.

**Comment by jcs090218** [comment] 2021-03-23 14:57
I think this is duplicate of #436? Can you grab the latest version and see if it work? Thanks!

**Comment by tastytea** [comment] 2021-03-23 16:09
In c++-mode (clangd), highlighting in lsp-ui-doc popups and eldoc was different before (can't remember what the difference was exactly), now it's the same.

**Comment by jcs090218** [comment] 2021-03-23 16:34
Great! I am going to close this for now. Feel free to reopen this if the issue remains.

**Closed by jcs090218** 2021-03-23 16:34 UTC
Labels: bug, duplicate, eldoc, ui-doc
