### ISSUE TITLE
Flycheck not updating after text changes

### ISSUE THREAD

**Issue by Coffei** [emacs-lsp/lsp-ui#300] opened 2019-06-25 14:42 UTC
Hi,
I am using lsp-mode/lsp-ui in emacs 26.2 with Spacemacs (on the develop branch) and started seeing this strange behaviour a couple weeks ago. The problem is flycheck shows errors only on first start-up of the server. So if I open a file, introduce an error and save the file, flycheck doesn't show anything, unless I restart the LSP server. Similarly, fixed errors don't disappear unless I restart the server.

I am using [JakeBecker/elixir-ls](https://github.com/JakeBecker/elixir-ls) and a config that closely resembles that in lsp-clients.el (also tried removing my config and taking exactly what is in lsp-clients.el and that didn't help), so I'm pretty sure I have the LSP configured well.

I turned on debugging but I don't see anything wrong, the server output seems to be OK. When I change the text I see `Sending notification textDocument/didChange` in the log, but no response (not sure if one is supposed to arrive).

I use the same elixir-ls server with VIM and that works just fine, also Spacemacs works fine with java lsp-backed layer, so not sure where the error resides, but this seemed like the place to start.

Any ideas where to start debugging this?

**Comment by yyoncho** [comment] 2019-06-25 16:15
fixed with https://github.com/emacs-lsp/lsp-mode/commit/ca3abb2f5503a378fc2acf6dd5bafa21165a99ff

The issue is that elixir ls does not declare that it wants didSave notifications. Vscode sends them no matter this flag. I have patched the code to send them. Let me know whether it works for you.

The strategy to diagnose that kind of issues is to compare with the vscode behaviour.

**Closed by yyoncho** 2019-06-25 16:15 UTC

**Comment by Coffei** [comment] 2019-06-26 06:57
That solves it, thank you!
I'll see if I can submit an issue/PR for elixir-ls to ask for the notification.
