### ISSUE TITLE
Can't get flycheck to work with lsp-ui

### ISSUE THREAD

**Issue by Gei0r** [emacs-lsp/lsp-ui#226] opened 2019-01-12 12:04 UTC
When I open a cpp file, lsp-ui with ccls does work (e.g., sideline mode). But flycheck doesn't seem to know anything about lsp-ui. `flycheck-verify-setup` gives:

```
Syntax checkers for buffer main.cpp in c++-mode:

  c/c++-clang
    - may enable: yes
    - executable: Found at c:/msys64/mingw64/bin/clang.exe

  c/c++-gcc
    - may enable: yes
    - executable: Found at c:/msys64/mingw64/bin/gcc.exe

  c/c++-cppcheck
    - may enable: Automatically disabled!
    - executable: Not found

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 32snapshot (package: 20190108.351)
Emacs version:    26.1
System:           x86_64-w64-mingw32
Window system:    w32
```

When I `(require 'lsp-ui-flycheck)`, there is the following addition:

```
The following syntax checkers are not registered:

  - lsp-ui

Try adding these syntax checkers to `flycheck-checkers'.
```
How do I enable lsp-ui-flycheck?

Here's the minimal `init.el`:

```
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t) (package-initialize)

(unless package-archive-contents (package-refresh-contents))  ; install use-package
(unless (package-installed-p 'use-package) (package-install 'use-package))

(eval-when-compile (require 'use-package)) (setq use-package-always-ensure t)

(use-package flycheck)
(add-hook 'c++-mode-hook 'flycheck-mode)

(use-package lsp-mode :commands lsp)
(use-package lsp-ui :commands lsp-ui-mode :hook (lsp-mode . lsp-ui-mode))
(use-package company-lsp :commands company-lsp)

(use-package ccls
  :hook ((c-mode c++-mode objc-mode) .
         (lambda () (require 'ccls) (lsp)))
  :config
  (setq ccls-executable "D:/Adrian/ccls/ccls/build/ccls.exe"))
```

**Comment by yyoncho** [comment] 2019-01-12 12:08
Did you try `(setq lsp-prefer-flymake nil)` before calling `lsp`?

**Comment by yyoncho** [comment] 2019-01-12 12:10
These are not needed: 
> :hook (lsp-mode . lsp-ui-mode)

> (add-hook 'c++-mode-hook 'flycheck-mode)

**Comment by Gei0r** [comment] 2019-01-12 18:18
OK, with setting `lsp-prefer-flymake` to `nil` it now looks better:

```
Syntax checkers for buffer main.cpp in c++-mode:

  lsp-ui
    - may enable: yes
    - predicate:  t

  c/c++-clang
    - may enable: yes
    - executable: Found at c:/msys64/mingw64/bin/clang.exe

  c/c++-gcc
    - may enable: yes
    - executable: Found at c:/msys64/mingw64/bin/gcc.exe

  c/c++-cppcheck
    - may enable: Automatically disabled!
    - executable: Not found

The following checker is explicitly selected for this buffer:

  lsp-ui
    - major mode: `c++-mode' supported
    - may enable: yes
    - predicate:  t

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 32snapshot (package: 20190108.351)
Emacs version:    26.1
System:           x86_64-w64-mingw32
Window system:    w32
```

But flycheck errors are still not displayed. For example, with this small cpp file, there's no error:

![flycheck](https://user-images.githubusercontent.com/16615274/51076875-b93df500-169e-11e9-8afb-f0afb00dbb31.png)

The buffers `*Flycheck errors*`, `*ccls*` and `*ccls::stderr*` are all empty, fwiw.

**Comment by yyoncho** [comment] 2019-01-12 18:55
AFAIK ccls reports the errors on save.

If this does not fix your issue, can you do: (setq lsp-print-io t) and inspect the messages that are sent from the server?

**Comment by Gei0r** [comment] 2019-01-12 19:06
Nothing happens on save either.

After setting `lsp-print-io`, I can see that the error *is* reported:

```
<<<< ccls:6988
{
  "jsonrpc": "2.0",
  "method": "textDocument/publishDiagnostics",
  "params": {
    "uri": "file:///D%3A/Adrian/ccls/testproj2/main.cpp",
    "diagnostics": [
      {
        "range": {
          "start": {
            "line": 5,
            "character": 4
          },
          "end": {
            "line": 5,
            "character": 18
          }
        },
        "severity": 1,
        "code": 2,
        "source": "ccls",
        "message": "use of undeclared identifier 'does_not_exist'"
      }
    ]
  }
}
```

... but it doesn't display it in the buffer.

I can see though that diagnostic messages are also produced by just typing wrong code (not only on save).

**Comment by yyoncho** [comment] 2019-01-12 19:11
I just tested the same setup and it works fine. 

Can you go in this file and do
`C-:`  `(buffer-file-name)` 
and 
`C-:` - `(lsp--uri-to-path "file:///D%3A/Adrian/ccls/testproj2/main.cpp")`

I suspect that there is filepath mismatch.

**Comment by yyoncho** [comment] 2019-01-12 19:13
Change `C-:` to `M-:`

**Comment by Gei0r** [comment] 2019-01-12 19:15
`(buffer-file-name)`: `"d:/Adrian/ccls/testproj2/main.cpp"`

`(lsp--uri-to-path "file:///D%3A/Adrian/ccls/testproj2/main.cpp")`: `"D:/Adrian/ccls/testproj2/main.cpp"`

So there's a difference in the driver letter (`D` vs `d`).

**Comment by Gei0r** [comment] 2019-01-12 19:33
The workaround doesn't work either unfortunately.

I won't be able to look into it anymore today, but I will continue trying it out tomorrow.

I'm quite ok with elisp. Maybe you can give me a hint as to where I can start debugging the issue, i.e. what functions I should watch in the debugger etc.?

**Comment by yyoncho** [comment] 2019-01-12 19:39
Here it is the list of functions:

`lsp--uri-to-path` - converts uri to file path
`lsp--on-diagnostics` - the function that receives the diagnostics and puts them into a hash-map and should trigger `lsp-after-diagnostics-hook`

`lsp-ui` is subscribed to `lsp-after-diagnostics-hook` and gets the errors for the current file from using `lsp-diagnostics` and converts them to flycheck errors in `lsp-ui-flycheck--start`

**Comment by yyoncho** [comment] 2019-01-12 19:44
Your issue is duplicate of https://github.com/emacs-lsp/lsp-mode/issues/343

**Comment by yyoncho** [comment] 2019-01-13 19:49
based on the description I believe that `lsp--on-diagnostics` does not trigger the hook, probably this returns nil: https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-mode.el#L847

**Comment by Gei0r** [comment] 2019-01-13 20:15
I don't know what caused it on windows, but now the hooks are set up correctly. I haven't changed anything...

Also I got it to work now by sprinkling `downcase`-calls all over the lsp(-ui) source code. Now I'll try to figure out which ones are required.

**Closed** 2019-01-15 12:38 UTC
