### ISSUE TITLE
Too much visible whitespace

### ISSUE THREAD

**Issue by alanz** [emacs-lsp/lsp-ui#159] opened 2018-07-21 09:31 UTC
Using `GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-05-07, modified by Debian`, and having set 

```
 '(global-whitespace-mode t)
 '(show-trailing-whitespace t)
 '(whitespace-style
   (quote
    (face trailing tabs spaces lines-tail newline empty indentation space-after-tab space-before-tab space-mark tab-mark newline-mark))))
 '(whitespace-line ((t (:background "light cyan"))))
 '(whitespace-space ((t (:foreground "lightgray"))))
``` 
I find that the hover windows have black dots in them to show the spaces.

![screenshot from 2018-07-21 11-27-21-annotated](https://user-images.githubusercontent.com/409607/43034249-817aaefa-8cd9-11e8-9a3d-18a7bff6543d.png)

I am not sure if this is a simple configuration issue, or something that needs to be changed.

**Comment by alanz** [comment] 2018-07-21 13:33
And my personal solution has been to finally install emacs 26.1 via source on my Debian testing machine.

**Comment by coreyoconnor** [comment] 2019-05-13 02:01
@alanz can you confirm this issue was resolved by installing emacs 26.1?

If this issue was resolved with 26.1 then I would presume the issue is/was with emacs not lsp-ui. Seem reasonable?

**Comment by brotzeit** [comment] 2020-03-03 20:56
Still an issue ?

**Comment by alanz** [comment] 2020-03-03 20:59
Not for me. But mainly because my config no longer shows whitespace as dots, and I am using the overlay form for the pop-up windows.

**Comment by brotzeit** [comment] 2020-03-03 20:59
I will keep an eye on this.

**Closed by brotzeit** 2020-03-03 20:59 UTC
