### ISSUE TITLE
lsp getting confused after just a few edits: typescript-language-server/web-mode/tsx

### ISSUE THREAD

**Issue by cwhatley** [emacs-lsp/lsp-ui#238] opened 2019-02-05 13:29 UTC
**Describe the bug**

lsp-ui/lsp 6.0

After a few edits to a file, there is some problem with communicating with the language server which results in a nonsensical flycheck error list. Restarting the server fixes the problem for a bit.

I have lsp-ui on top with flycheck instead of flymake.

**To Reproduce**

Edit any sizable TSX file under web-mode with typescript-language-server installed in your path.

I can usually get it to happen when I go to a line, add some garbage lines plus some garbage at beginning of existing line. Then delete garbage lines and finally clean up the existing line I changed.

My only customization:

```
(setq-default lsp-prefer-flymake nil)
```

**Expected behavior**
The flycheck errors should go away.

**Which Language Server did you use**
typescript-language-server

**OS**
Which os do you use?
MacOS with emacs-mac and emacs-plus brew installs. Ubuntu 18.04 with emacs 26.1.

**Error callstack**
There is no error callstack.

![screen shot 2019-02-04 at 10 12 08 pm](https://user-images.githubusercontent.com/573757/52253287-f7f95080-28d4-11e9-9063-45fbfd6cccde.png)

The LSP log is here. Note that the specific 2304 typescript error doesn't show up in the log at all, but perhaps it scrolled off the log.

[lsp-log.txt](https://github.com/emacs-lsp/lsp-ui/files/2832239/lsp-log.txt)

**Comment by yyoncho** [comment] 2019-02-06 17:23
Possible dup of https://github.com/emacs-lsp/lsp-ui/issues/237 ?

**Comment by cwhatley** [comment] 2019-02-06 17:29
Definitely seems similar, but in the case I'm experiencing, I can navigate around the file and the overlay with the incorrect info is properly hidden and replaced with content from other lines. When I return to the line, I get the incorrect info again.

There are also often bits of underlines left around on top the code where errors once were and the flymake error list buffer when shown always shows the incorrect info until the LSP session is restarted.

One thing I noticed that seemed kind of odd is that when I run (lsp-diagnostics) and look at the hash entry for the file in question, I see a list that contains a few diag structs and then as its final element there's another list containing a copy of the preceding elements of the main diag list. E.g., like `(diag1 diag2 (diag1 diag2))`. Not obvious to me from a scan of the code that that is intentional.

**Comment by yyoncho** [comment] 2019-02-06 18:33
Can you check lsp-ui-flycheck-list and flycheck-buffer content? I want to diagnose whether the issue is in lsp-mode failing to handle diagnostics properly or lsp-ui failing to cleanup cache. 

> E.g., like `(diag1 diag2 (diag1 diag2))`. Not obvious to me from a scan of the code that that is intentional

This is probably caused by the fact that each diagnostic contains its original value (the diagnostic that is comming from lsp server).

**Comment by cwhatley** [comment] 2019-02-07 00:30
For this error:

![image](https://user-images.githubusercontent.com/573757/52381521-c3ee6e80-2a3f-11e9-9401-ed95424d5dcb.png)

Flycheck:

![image](https://user-images.githubusercontent.com/573757/52381539-d1a3f400-2a3f-11e9-8f90-ece0fb7b4670.png)

The output of `M-: RET (lsp-ui-flycheck-list)` appears totally unrelated to what's shown:

![image](https://user-images.githubusercontent.com/573757/52381564-e4b6c400-2a3f-11e9-9f96-fc18e30a92df.png)

Attached below is a pretty minimal init.el where I can still make the problem happen:

[issue-238-init.el.txt](https://github.com/emacs-lsp/lsp-ui/files/2838803/issue-238-init.el.txt)

Also, FYI, I have the latest typescript-language-server 0.3.7.

**Comment by cwhatley** [comment] 2019-02-07 00:34
Hmm. I just tried removing the typescript-language-server and adding javascript-typescript-langserver and now I am not seeing the problem anymore.

**Comment by yyoncho** [comment] 2019-02-07 06:41
I am not js/ts user so do you have a sample project which I can use to try to reproduce the issue? From what I can see the js-ts language server messes up and does not clear the errors but I cannot determine that since the log is truncated( you may change the number of stored lines via lsp-log-max ). 

> Also, FYI, I have the latest typescript-language-server 0.3.7.

Do you have the latest `typescript` package as well? `typescript-language-server` is using it.

**Comment by cwhatley** [comment] 2019-02-08 18:38
Recipe:

```
npx create-react-app lsp-ts-fu-test --typescript
```

Replace src/index.tsx in the project with the attachment here:

[index.tsx.zip](https://github.com/emacs-lsp/lsp-ui/files/2846398/index.tsx.zip)

Visit src/index.tsx and go to line 25 and put your cursor on the opening quote of `"maths"`

Run this macro:

```                                                                                   
(fset 'typescript-fubar
   "pojawfpojawe\C-mfawe\C-mf\C-mawef\C-mawe\C-mef\C-mawe\C-mf\C-mawef\C-mw\C-m\C-m\C-[f\C-f\C-e\C-m\C-mawef\C-maw\C-mef\C-mawe\C-mfaw\C-mef\C-mwaef\C-m\C-a\C-p\C-p\C-p\C-p\C-p\C-k\C-k\C-k\C-k\C-k\C-k\C-k\C-k\C-a\C-p\C-p\C-p\C-p\C-n\C-k\C-k\C-k\C-k\C-k\C-k\C-k\C-i\C-a\C-?\C-a\C-p\C-p\C-n\C-nwefwef\C-p\C-a\C-@\C-p\C-p\C-p\C-p\C-p\C-p\C-w\C-p\C-p\C-p\C-p\C-p\C-p\C-p\C-p\C-n\C-n\C-n\C-n\C-n\C-p\C-@\C-n\C-n\C-n\C-n\C-w\C-d\C-[d\C-d\C-i")
```

You should see something like this:

![image](https://user-images.githubusercontent.com/573757/52498441-ce774800-2ba6-11e9-83ed-abb019d3d970.png)

**Comment by yyoncho** [comment] 2019-02-08 20:10
we need to fix https://github.com/emacs-lsp/lsp-mode/issues/588#issuecomment-450737726 before recommending this server. 

I had some troubles replying the macro - might be caused by my heavily customized environment. I will try it tomorrow with `emacs -q` and using your setup(hopefully it will reproduce) and emacs 26.1.

**Comment by yyoncho** [comment] 2019-02-08 20:21
> Also, FYI, I have the latest typescript-language-server 0.3.7.

Do you use the latest version of `typescript` (tsserver) as well?

**Comment by cwhatley** [comment] 2019-02-08 21:42
The sample project above created by create-react-app will use typescript 3.3.3 which is the latest. The language server launches the tsserver from within the project (at least I'm pretty sure it does b/c I don't have it installed globally).

**Comment by yyoncho** [comment] 2019-02-09 05:29
@cwhatley I reproduced it on my side, it seems like either lsp-mode is sending incorrect text edits, or typescript language server handles them wrongly.

**Comment by yyoncho** [comment] 2019-02-09 07:37
@cwhatley I am on to it - the issue is that typescript messes up I am still trying to figure out what is the reason for that.

I added logs in document.js from the typescript-language-server and here it is the output: https://gist.github.com/yyoncho/fdb06e4909d60010cab5fab0c57f7be7

**Comment by yyoncho** [comment] 2019-02-09 08:32
@cwhatley can you verify that  ```(setq indent-line-function nil)``` fixes the issue on your side. It seems like the changes performed by this function are not reported as changes and lsp-mode is missing them.

**Comment by cwhatley** [comment] 2019-02-09 21:19
Yes. I set indent-line-function to nil and I have been unable to recreate the problem since.

**Comment by yyoncho** [comment] 2019-02-11 18:52
Given the lower impact/the amount of open issues/the presence of a workaround I propose to close this bug as `won't fix`/`workaround` and document it in lsp-mode FAQ section.

**Comment by cwhatley** [comment] 2019-02-11 19:18
Is the workaround the nullifying of indent-line-function or using the other langserver? Nullifying indent-line-function would be pretty detrimental to the use of web-mode.

Do you have any idea what web-mode-indent-line is doing that causes the change to not get picked up by LSP?

**Comment by yyoncho** [comment] 2019-02-11 19:29
@cwhatley
> Is the workaround the nullifying of indent-line-function

Nullifying the indent-line-function.

> Do you have any idea what web-mode-indent-line is doing that causes the change to not get picked up by LSP?

It inserts the indentation in a way that breaks the change hook execution. (`lsp-on-change` does not receive the proper start/end/length ).

**Comment by cwhatley** [comment] 2019-02-11 23:04
Ah, so I think I see what the issue is. For whatever reason, web-mode-indent-line has a let that sets`inhibit-modification-hooks` to t. This prevents the `lsp-on-change` from getting fired in the `after-change-functions hook`.

I just posted an issue for web-mode here: https://github.com/fxbois/web-mode/issues/1039

**Comment by yyoncho** [comment] 2019-03-06 19:11
The fix in web-mode is in, thus closing the PR.

**Closed by yyoncho** 2019-03-06 19:11 UTC
