### ISSUE TITLE
lsp-ui-peek-find-references doesn't highlight identifier in code lens in php files.

### ISSUE THREAD

**Issue by ilyaguy** [emacs-lsp/lsp-ui#393] opened 2020-02-12 07:48 UTC
lsp-ui version 20200209.955
php-mode version 20200121.1613

In file list highlighting works fine, but in code — don't

![screenshot.png](https://user-images.githubusercontent.com/6704355/74313642-bcf9ea80-4d7c-11ea-93e7-dbbbebdc84f9.png)

**Comment by yyoncho** [comment] 2020-02-16 15:12
Duplicate of #278

**Closed by yyoncho** 2020-02-16 15:12 UTC
