### ISSUE TITLE
lsp-ui-sideline does not hide after buffer is reverted

### ISSUE THREAD

**Issue by Yevgnen** [emacs-lsp/lsp-ui#237] opened 2019-02-03 13:07 UTC
When some messages are being displayed by `lsp-ui` and the buffer is reverted by `M-x revert-buffer`, these messages are kept displaying all the time even the cursor has moved.

![fdsa](https://user-images.githubusercontent.com/16749790/52177134-a75ff580-27f7-11e9-86fb-b2df7dce5174.gif)

**Comment by yyoncho** [comment] 2019-02-03 17:11
The issue is in the lsp-ui, for some reason the overlay is not deleted after revert.

**Comment by SerialVelocity** [comment] 2019-02-13 16:00
Is there a workaround we can apply now that isn't closing and re-opening the buffer when it happens? Turning off `lsp-ui-mode` and `lsp-ui-sideline-mode` doesn't seem to help

**Comment by yyoncho** [comment] 2019-02-13 19:59
@SerialVelocity  Please test https://github.com/emacs-lsp/lsp-ui/pull/240

**Comment by SerialVelocity** [comment] 2019-02-13 20:18
Seems to work for me. I can no longer repo the issue after reverting the buffer. Thanks @yyoncho!

**Closed** 2019-02-14 16:15 UTC
Labels: bug
