### ISSUE TITLE
Sideline wraps to begining of next line, pushing code lines down

### ISSUE THREAD

**Issue by XO39** [emacs-lsp/lsp-ui#597] opened 2021-03-25 15:53 UTC
This happens after updating to `v20210324.1217` I believe it has to do with commit #595 (or maybe #594), as I downgraded to #592 and the issue was gone.

Emacs v27.1 (9.0)
MacOS v11.2.3 
LSP v20210321.1904

As you can see from the attached pictures, the wrapping is somehow related to the `point` position, the farther the cursor moves to the right, the more text got wrapped.

<img width="1262" alt="01" src="https://user-images.githubusercontent.com/47403233/112502241-e0d39080-8dc4-11eb-860d-fd636b54a438.png">
<img width="1278" alt="02" src="https://user-images.githubusercontent.com/47403233/112502262-e5984480-8dc4-11eb-8880-3adbfbab20f9.png">
<img width="1273" alt="03" src="https://user-images.githubusercontent.com/47403233/112502267-e7620800-8dc4-11eb-8619-6d0286854813.png">

Sideline should not wrap as it push code down and make the screen very jumpy, too annoying and almost impossible to work with.

**Comment by jcs090218** [comment] 2021-03-25 15:57
@XO39 @Yevgnen I think the issue is `truncate-lines` and `text-scale-mode`. Do you guys have either of these minor mode enabled? (for truncate-lines should be disabled)

**Comment by Yevgnen** [comment] 2021-03-25 16:16
@jcs090218 Nope, neither.

**Comment by jcs090218** [comment] 2021-03-25 17:07
I have tried to apply a patch in #596. 

![ezgif-2-79217fe41c2d](https://user-images.githubusercontent.com/8685505/112513797-a8857f80-8dcf-11eb-91a8-2a7efc595d0e.gif)

**Comment by Yevgnen** [comment] 2021-03-25 17:16
The fix seems not work for me.

<img width="952" alt="Screen Shot 2021-03-26 at 1 15 22 AM" src="https://user-images.githubusercontent.com/16749790/112515058-e636d800-8dd0-11eb-8aef-eb11410794a1.png">

**Comment by XO39** [comment] 2021-03-25 18:20
> @XO39 @Yevgnen I think the issue is `truncate-lines` and `text-scale-mode`. Do you guys have either of these minor mode enabled? (for truncate-lines should be disabled)

Both of these are nil, and the #596 patch didn't work for me either.

**Comment by alanz** [comment] 2021-03-25 18:32
I can confirm it does not work for me either (GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23, cairo version 1.16.0) of 2020-11-07, modified by Debian)

The offset is correct if my cursor is in the extreme left of the buffer, the code actions dynamically move if I move my cursor to the right.

**Comment by jfkw** [comment] 2021-03-25 20:07
My emacs-27.1 is with `lsp-ui` in default config is exhibiting the same behavior. The specific example is when point enters a string literal argument to `println!`. I attached the full resolution screenshots to illustrate that there's sufficient room for the overlay at the right hand side if the position is calculated correctly.

x-special/nautilus-clipboard
copy
file:///home/jkowalczyk/lsp-ui-problem-01.png
file:///home/jkowalczyk/lsp-ui-problem-02.png
file:///home/jkowalczyk/lsp-ui-problem-03.png

**Comment by jcs090218** [comment] 2021-03-25 21:58
Okay let me revert the changes.

**Comment by jfkw** [comment] 2021-03-26 04:35
Following commit 14de2a697e13fa151650296c9be053826378c9bd, the issue when point is in a regular literal string as shown above is fixed, thanks. However, accepting the suggested code fix to "Rewrite as raw string", then the inverse "Rewrite as regular string Add Remove" affects the first character of the preceding line and inserts lines for "Add" and "Remove" causing the code at point to shift position. The attached screenshot shows this state. Note how "Rewrite as regular stringp" has taken the "p" from function signature "pub" and moved it out of position.

![lsp-ui-problem-04](https://user-images.githubusercontent.com/12948/112577604-e07dca00-8db1-11eb-993f-707c6a5db9d7.png)

**Comment by jcs090218** [comment] 2021-03-26 04:49
Does this only occurred in the first line?

**Comment by jfkw** [comment] 2021-03-26 04:59
Yes, it only appears to be a problem on the first line, which isn't likely to be a distraction in normal use. Thanks for the quick follow-up.

![lsp-ui-problem-06](https://user-images.githubusercontent.com/12948/112584526-3dc74a80-8db5-11eb-9a62-f12c1cd84dc1.png)

![lsp-ui-problem-07](https://user-images.githubusercontent.com/12948/112584543-44ee5880-8db5-11eb-8df0-f43217199d81.png)

**Comment by jcs090218** [comment] 2021-03-26 05:06
This would be an different issue since I have made a PR in #593 and this would display the sideline in the first line. Originally, sideline would avoid to display in the first line and I assumed this should be fixed. TBH, I don't know if this is a bug or a design decision. Anyway, I am not able to reproduce this issue too...

@jfkw Can you open a new issue for this? I would close this issue now since I have reverted the changes and the following discussion is irrelevant to the original issue.

Thanks!

**Closed by jcs090218** 2021-03-26 05:06 UTC

**Comment by zwizwa** [comment] 2022-04-09 23:11
Not sure if it's related, but I ran into an issue with wrapping lines when using a fixed font (terminus). In that case, setting font face height to any value other than 'unspecified will case it to switch to a different font. Overriding this function (e.g. in use-package :config section) will work around that:

`  (defun lsp-ui-sideline--compute-height nil '(height unspecified))
`
