### ISSUE TITLE
lsp-mode codelens

### ISSUE THREAD

**Issue by innerout** [emacs-lsp/lsp-ui#153] opened 2018-06-30 22:58 UTC
Is it possible to have lsp-ui show the codelens references in its lsp-ui-peek-find-references function?

**Comment by MaskRay** [comment] 2018-09-18 16:48
Can you elaborate this a bit?

**Comment by yyoncho** [comment] 2018-09-18 17:01
Duplicate of https://github.com/emacs-lsp/lsp-ui/issues/132 . Showing code lenses in the sideline does not seem like a good idea since there could be several elements on the line which do have code lens so it wont be possible to distinguish the target. Something similar to https://github.com/cpitclaudel/quick-peek might do the job.

**Comment by innerout** [comment] 2018-09-18 18:44
I like more the suggestion of @yyoncho with quick-peek . My initial idea was to have codelens printed in a window similar to lsp-ui-peek-find-references but i did not describe it properly.

**Comment by MaskRay** [comment] 2018-09-19 02:14
Can we close it then?

**Closed by MaskRay** 2018-09-19 02:14 UTC
